version: "3.7" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의 ( 컴포즈에서 컨테이너 : 서비스 )
  db: # 서비스 명
    image: mysql:8.0.23
    platform: linux/amd64
    restart: always
    container_name: nestjs-template # 컨테이너 이름 설정
    ports:
      - 3306:3306 # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=nestjs
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_USER=nestjs
      - MYSQL_PASSWORD=0000
    command:
      - --log-bin=mysql-bin
      - --server-id=1
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
